name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: python -m pip install -U pip
      - run: pip install -e ".[dev,tokens]"
      - run: ruff --version && mypy --version
      - run: ruff .
      - run: mypy src/gridwise
      - run: pytest --maxfail=1 --disable-warnings -q